# Generated by Django 3.2.14 on 2022-07-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
