# Generated by Django 3.2.14 on 2022-07-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_alter_link_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
